### ISSUE TITLE
when onnx model using avgpool, has a ValueError: not enough values to unpack (expected 10, got 8) in optimizer.py

### ISSUE THREAD

**Issue by CRhapsody** [eth-sri/eran#68] opened 2021-04-10 04:54 UTC
Traceback (most recent call last):
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 1345, in <module>
    label,nn,nlb,nub,_,_ = eran.analyze_box(specLB, specUB, init_domain(domain), config.timeout_lp, config.timeout_milp, config.use_default_heuristic)
  File "./eran.py", line 89, in analyze_box
    execute_list, output_info = self.optimizer.get_deepzono(nn,specLB, specUB)
  File "./optimizer.py", line 310, in get_deepzono
    self.get_abstract_element(nn, 1, execute_list, output_info, 'deepzono')
  File "./optimizer.py", line 173, in get_abstract_element
    image_shape, window_size, strides, pad_top, pad_left, pad_bottom, pad_right, input_names, output_name, output_shape = self.resources[i][domain]
ValueError: not enough values to unpack (expected 10, got 8)

**Comment by mnmueller** [comment] 2021-04-10 14:21
Hello @CRhapsody,

Thanks for your interest in ERAN. I have updated ERAN and ELINA to fix this issue.
For future inquiries we would like to ask you to please provide the network causing the issue as the onnx format is sometimes quite sensitive to the exact network and settings used.

Cheers, 
Mark

**Comment by CRhapsody** [comment] 2021-04-11 04:28
Thank you for your reply. I would like to explain several problems encountered in the processing.  @mnmueller 

1.I used tf. Keras library to program the Resnet18 network myself, and used tf2onnx to convert the model to ONNX model, the libraries' version are as follows:

tensorflow           2.4.1

tf2onnx                1.9.0

torch                     1.8.1

onnx                   1.5.0

onnxruntime            1.7.0

The parameter opset is 8.

For parameter --domain, I took gpuploy, then an error occurred when running ERAN:

Traceback (most recent call last):
File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "./__main__.py", line 475, in <module>
translator = ONNXTranslator(model, True)
File "./onnx_translator.py", line 388, in __init__
self.shape_map, self.constants_map, self.output_node_map, self.input_node_map, self.placeholdernames =
prepare_model(model)
File "./onnx_translator.py", line 358, in prepare_model
assert 0, "Operations of type " + node.op_type + " are not yet supported."
AssertionError: Operations of type ReduceMean are not yet supported.

After checked onnx model architecture, I found that problems occured when the layers generating by tf.Keras.layers.GlobalAveragePooling2Davgpool () method converted into onnx model, which node type is reducemean type. I looked up onnx_translate.py and found that no such node type was handled in the file.

2.I took tf.keras.layers.AveragePooling2D() and tf.keras.layers.Flatten() instead  of tf.keras.layers.GlobalAveragePooling2Davgpool(),then convert the new model to onnx model.

For parameter --domain, I took gpuploy, then an error occurred when running ERAN:

Traceback (most recent call last):
File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "./__main__.py", line 481, in <module>
network, relu_layers, num_gpu_layers = optimizer.get_gpupoly(nn) 
File "./optimizer.py", line 577, in get_gpupoly
assert 0, "the optimizer for" + "gpupoly" + " doesn't know of the operation type " + self.operations[i]
AssertionError: the optimizer forgpupoly doesn't know of the operation type Resadd

The error is same as above.

3.I modify the --domain parameter from gpuploy to deepploy，an error occurred when running ERAN:

Traceback (most recent call last):
File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "./__main__.py", line 1345, in <module>
label,nn,nlb,nub,_,_ = eran.analyze_box(specLB, specUB, init_domain(domain), config.timeout_lp, config.timeout_milp, config.use_default_heuristic)
File "./eran.py", line 96, in analyze_box
execute_list, output_info = self.optimizer.get_deeppoly(nn, specLB, specUB, lexpr_weights, lexpr_cst, lexpr_dim, uexpr_weights, uexpr_cst, uexpr_dim, expr_size, spatial_constraints)
File "./optimizer.py", line 443, in get_deeppoly
File "./optimizer.py", line 173, in get_abstract_element
image_shape, window_size, strides, pad_top, pad_left, pad_bottom, pad_right, input_names, output_name, output_shape = self.resources[i][domain]
ValueError: not enough values to unpack (expected 10, got 8)

My onnx file is so big that I can't upload it to github,so if you would like to ask me to provide my onnx file or tensorflow model, please give me your email or other methods, thank you.

**Comment by CRhapsody** [comment] 2021-04-11 04:48
For
"
3.I modify the --domain parameter from gpuploy to deepploy，an error occurred when running ERAN:

Traceback (most recent call last):
File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "./__main__.py", line 1345, in <module>
label,nn,nlb,nub,_,_ = eran.analyze_box(specLB, specUB, init_domain(domain), config.timeout_lp, config.timeout_milp, config.use_default_heuristic)
File "./eran.py", line 96, in analyze_box
execute_list, output_info = self.optimizer.get_deeppoly(nn, specLB, specUB, lexpr_weights, lexpr_cst, lexpr_dim, uexpr_weights, uexpr_cst, uexpr_dim, expr_size, spatial_constraints)
File "./optimizer.py", line 443, in get_deeppoly
File "./optimizer.py", line 173, in get_abstract_element
image_shape, window_size, strides, pad_top, pad_left, pad_bottom, pad_right, input_names, output_name, output_shape = self.resources[i][domain]
ValueError: not enough values to unpack (expected 10, got 8)
"
This problem is solved by using your update, thank you!

**Comment by CRhapsody** [comment] 2021-04-12 03:45
And,when I use resnet18 from torchvision.models.resnet,an error occured
Traceback (most recent call last):
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 475, in <module>
    translator = ONNXTranslator(model, True)
  File "./onnx_translator.py", line 388, in __init__
    self.shape_map, self.constants_map, self.output_node_map, self.input_node_map, self.placeholdernames = prepare_model(model)
  File "./onnx_translator.py", line 358, in prepare_model
    assert 0, "Operations of type " + node.op_type + " are not yet supported."
AssertionError: Operations of type GlobalAveragePool are not yet supported.

**Comment by mnmueller** [comment] 2021-04-12 11:55
Hello @CRhapsody,

This is expected, as we do not yet support the GlobalAveragePooling operation. 
However, you should be able to replace it with a standard Average Pooling layer with a suitable kernel size followed by a flatten layer.

Cheers,
Mark

**Comment by CRhapsody** [comment] 2021-04-12 12:25
> Hello @CRhapsody,
> 
> This is expected, as we do not yet support the GlobalAveragePooling operation.
> However, you should be able to replace it with a standard Average Pooling layer with a suitable kernel size followed by a flatten layer.
> 
> Cheers,
> Mark

Thank you, I replace it with Average Pooling layer with a suitable kernel size followed by a flatten layer. However, a new error occured

Traceback (most recent call last):
File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "./main.py", line 481, in
network, relu_layers, num_gpu_layers = optimizer.get_gpupoly(nn)
File "./optimizer.py", line 577, in get_gpupoly
assert 0, "the optimizer for" + "gpupoly" + " doesn't know of the operation type " + self.operations[i]
AssertionError: the optimizer forgpupoly doesn't know of the operation type Resadd.

When I changed domain from "gpupoly"  to "deepploy", this error disappered, but it cost much more time than gpu version.

**Comment by mnmueller** [comment] 2021-04-12 12:38
Hello @CRhapsody,

Unfortunately, the current gpupoly implementation does not yet support residual connections so this is expected behaviour and you will have to use deeppoly for now.
We plan to add this functionality soon.

Cheers,
Mark

**Comment by CRhapsody** [comment] 2021-04-13 10:27
Thank you @mnmueller 

When I use googLenet model from torchvision.models.googlenet, an error occured(choose the parameter domain is 'deepploy'):

Traceback (most recent call last):
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 1345, in <module>
    label,nn,nlb,nub,_,_ = eran.analyze_box(specLB, specUB, init_domain(domain), config.timeout_lp, config.timeout_milp, config.use_default_heuristic)
  File "./eran.py", line 103, in analyze_box
    dominant_class, nlb, nub, failed_labels, x = analyzer.analyze(terminate_on_failure=terminate_on_failure)
  File "./analyzer.py", line 207, in analyze
    element, nlb, nub = self.get_abstract0()
  File "./analyzer.py", line 183, in get_abstract0
    self.use_default_heuristic, self.testing)
  File "./deeppoly_nodes.py", line 618, in transformer
    handle_pool_layer(man, element, (c_size_t *3)(h,w,1), (c_size_t *3)(H, W, C), (c_size_t *2)(self.strides[0], self.strides[1]), self.pad_top, self.pad_left, self.pad_bottom, self.pad_right, self.output_shape, self.predecessors, len(self.predecessors), self.is_maxpool)

Then I change the domain into 'gpuploy', an error occured:

Traceback (most recent call last):
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 481, in <module>
    network, relu_layers, num_gpu_layers = optimizer.get_gpupoly(nn) 
  File "./optimizer.py", line 577, in get_gpupoly
    assert 0, "the optimizer for" + "gpupoly" + " doesn't know of the operation type " + self.operations[i]
AssertionError: the optimizer forgpupoly doesn't know of the operation type MaxPool

After that, I checked the optimizer.py. I found that it doesn't have operation type MaxPool and Avgpool.

**Comment by mnmueller** [comment] 2021-04-13 11:17
Hello @CRhapsody,
I think the line actually indicating what the error was might be missing in the error message you pasted in the first case. Please be sure to include this for me to look into this problem.

And this is correct, they are currently not supported for GPUPoly.

Cheers,
Mark

**Comment by CRhapsody** [comment] 2021-04-13 13:18
> Hello @CRhapsody,
> I think the line actually indicating what the error was might be missing in the error message you pasted in the first case. Please be sure to include this for me to look into this problem.
> 
> And this is correct, they are currently not supported for GPUPoly.
> 
> Cheers,
> Mark

Sorry, I don't understand what exactly I need to provide. Please tell me more about it.

**Comment by CRhapsody** [comment] 2021-04-17 14:12
Hello @mnmueller 
A new error occurred when I verified my FNN model, which only has Relu and full connected layer. 
I convert an image (32*32*3) to numpy array (1*3072) , then I save it to csv file with the formal as "cifar10_test.csv".
I run this command get the output A:

python3 . --netname ../test_net_tll.onnx --epsilon 0 --domain deeppoly --dataset cifar10 --mean 0 0 0 --std 1 1 1

The "test_net_tll.onnx" is my FNN model converted to Onnx model. 
Then I run the command "model(x)" in python to get the output B of this image.

Comparing A with B, I found that two output are different, but I set the epsilon is zero.

**Comment by mnmueller** [comment] 2021-04-18 10:20
Hello @CRhapsody,

Regarding your first question:
Can you please make sure that both your ERAN and ELINA version are up to date (and freshly compiled for ELINA). The problem with handling pool layers should have been resolved in the past and I can't reproduce it with the current version.

Regarding your second question:
This typically happens, if nchw (batch, channel, height, width) data format is assumed in one place and nhwc in another. Please try to permute the second and fourth dimension of your image, before flattening and check, if this resolves your issue. 
If this does not help, could you create an example with a very small network, that you can upload here, so that I can try to reproduce the issue?

Cheers,
Mark

**Comment by CRhapsody** [comment] 2021-04-18 13:03
Thank you @mnmueller 

Regarding the first question:
I installed ERAN and ELINA in 9 days ago. I just update the file in "tf-verify", run this command

python3 . --netname ../test_google.onnx --epsilon 0 --domain deeppoly --dataset cifar10 --mean 0 0 0 --std 1 1 1

but the error don't estimate.

Regarding the second question:
I think two interface, model and image, should be the same:
(1) my model: 
the preprocessing of dateset is as follows using pytroch:

tf = transforms.Compose([
            lambda x:Image.open(x).convert('RGB'), # string path= > image data
            transforms.Resize((32, 32)),
            transforms.ToTensor()
])

After this preprocessing, the shape of data is (3x32x32).

(2)my data
I try there kinds of data of image with the preprocessing:

tf = transforms.Compose([
            lambda x:Image.open(x).convert('RGB'), # string path= > image data
            transforms.Resize((32, 32)),
            transforms.ToTensor(),
            transforms.ToPILImage() #convert the tensor to image format (32,32,3) with no normalization

])


Then I use permute to make the data for three format: nchw, nhwc and nwhc data before flattening. But these three kinds of output for three format data with command:

python3 . --netname ../test_net_tll.onnx --epsilon 0 --domain deeppoly --dataset cifar10 --mean 0 0 0 --std 1 1 1

are all different with model(x).


(3) I don't know how to upload file in issue, so I update my model and example image to my repository [My-problem-of-ERAN](https://github.com/CRhapsody/My-problem-of-ERAN), you can download them from there.

**Comment by mnmueller** [comment] 2021-04-26 09:50
Hello @CRhapsody,

Regarding the first issue: 
Please update both the full ELINA and ERAN version and check if you can still reproduce the error. I was unable to do so and the corresponding problem should have been fixed already.

Regarding your second problem:
Your networks is in nchw format. Since you did not provide a sample in csv format, I used a standard CIFAR10 sample in csv format, where dimensions can be restored with `.reshape(32,32,3)` and applied the following transform (before generating SpecLB and SpecUB in the __main__.py file), to obtain the same results with ERAN as I got when applying the onnx model directly to the same sample:
```
image = image.reshape(3,32,32).transpose((1,2,0)).reshape(-1)
```
Since you did not provide a sample in csv format, you might have to try other reshape transpose combinations, to recover the right ordering.

**Closed** 2021-05-05 21:31 UTC
