### ISSUE TITLE
Installation issue with no gpu

### ISSUE THREAD

**Issue by CAS-LRJ** [eth-sri/eran#45] opened 2020-12-07 10:58 UTC
Hello, I want to install ERAN and try refinepoly on a virtual machine with no cuda support. I followed the instructions on GitHub pages, but something wrong happened when I ran the example.

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 24, in <module>
    from eran import ERAN
  File "./eran.py", line 20, in <module>
    from optimizer import *
  File "./optimizer.py", line 20, in <module>
    from gpupoly import Network
  File "../ELINA/python_interface/gpupoly.py", line 31, in <module>
  File "../ELINA/python_interface/gpupoly.py", line 38, in Network
  File "/usr/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libgpupoly.so: cannot open shared object file: No such file or directory

There is a line "from gpupoly import Network" in optimizer.py. Without cuda support, I cannot install gpupoly from ELINA and that may cause the error in ERAN. Could you please check if it is really a problem or just something wrong with my installation? Thanks a lot!

**Comment by GgnDpSngh** [comment] 2020-12-08 02:06
Hi there,

Thanks for the feedback. I have pushed a fix to deal with this issue. Let me know if it works.

Cheers,
Gagandeep Singh

**Comment by CAS-LRJ** [comment] 2020-12-08 02:57
> Hi there,
> 
> Thanks for the feedback. I have pushed a fix to deal with this issue. Let me know if it works.
> 
> Cheers,
> Gagandeep Singh

It works.  Thanks for the quick fix! 👍

**Closed** 2020-12-08 21:52 UTC

**Comment by huanzhang12** [comment] 2021-03-24 05:56
@GgnDpSngh It seems this issue is happening again using latest ERAN. It was broken since commit 9c0d85396074103aa112fa1f00c2227bc9668292

https://github.com/eth-sri/eran/blob/a87e0a0ba94ffa58bbb947e1094278b6d8cf6670/tf_verify/optimizer.py#L21-L24

**Comment by mnmueller** [comment] 2021-03-24 08:49
@huanzhang12 Thanks for the feedback. It should be fixed now.
Now it is also possible to use GPUPoly when specified only via command-line arguments and not the config file and a more meaningful error message is provided when a GPU domain is selected, but GPUPoly not installed.

**Comment by huanzhang12** [comment] 2021-03-24 09:59
@mnmueller Thank you Mark for the fast response! I can confirm it works for me now :slightly_smiling_face:
